window:
  padding:
    x: 10
    y: 8
  decorations: full
  opacity: 0.97

font:
  normal:
    family: MesloLGM Nerd Font
    style: Regular
  bold:
    family: MesloLGM Nerd Font
    style: Bold
  italic:
    family: MesloLGM Nerd Font
    style: Italic
  size: 12.0
  offset:
    x: 0
    y: 1

cursor:
  style: Beam
  blink: true

colors:
  primary:
    background: "#24283b"
    foreground: "#c0caf5"
  normal:
    black: "#1d202f"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#7dcfff"
    white: "#a9b1d6"
  bright:
    black: "#414868"
    red: "#f7768e"
    green: "#9ece6a"
    yellow: "#e0af68"
    blue: "#7aa2f7"
    magenta: "#bb9af7"
    cyan: "#7dcfff"
    white: "#c0caf5"

shell:
  program: /run/current-system/sw/bin/fish

env:
  TERM: xterm-256color

key_bindings:
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: N, mods: Command, action: SpawnNewInstance }
